export const containerStyle = {
  maxWidth: "100%",
  minHeight: "100%",
};

export const londonCoords = {
  lat: 51.519977,
  lng: -0.128115,
};

export const data = [
  {
    DataProvider: {
      WebsiteURL: "http://openchargemap.org",
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 1,
        Title: "Manual Data Entry",
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License: "Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)",
      DateLastImported: null,
      ID: 1,
      Title: "Open Charge Map Contributors",
    },
    OperatorInfo: {
      WebsiteURL: "https://www.bppulse.co.uk/",
      Comments: "Formerly known as Polar Network, or BP Chargemaster",
      PhonePrimaryContact: "01582 400331",
      PhoneSecondaryContact: null,
      IsPrivateIndividual: false,
      AddressInfo: null,
      BookingURL: null,
      ContactEmail: "polarenquiries@chargemasterplc.com",
      FaultReportEmail: "polarenquiries@chargemasterplc.com",
      IsRestrictedEdit: false,
      ID: 32,
      Title: "BP Pulse",
    },
    UsageType: {
      IsPayAtLocation: false,
      IsMembershipRequired: true,
      IsAccessKeyRequired: true,
      ID: 4,
      Title: "Public - Membership Required",
    },
    StatusType: {
      IsOperational: true,
      IsUserSelectable: true,
      ID: 50,
      Title: "Operational",
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 200,
      Title: "Submission Published",
    },
    UserComments: null,
    PercentageSimilarity: null,
    MediaItems: null,
    IsRecentlyVerified: false,
    DateLastVerified: "2019-04-25T05:16:00Z",
    ID: 115225,
    UUID: "FC9992FD-0E66-45DE-A71B-21774C5955AF",
    ParentChargePointID: null,
    DataProviderID: 1,
    DataProvidersReference: null,
    OperatorID: 32,
    OperatorsReference: "24336",
    UsageTypeID: 4,
    UsageCost: "Inclusive; for Polar Plus subscription members only",
    AddressInfo: {
      ID: 115571,
      Title: "Coldra Court Hotel By Celtic Manor",
      AddressLine1: "Langstone",
      AddressLine2: null,
      Town: "Newport",
      StateOrProvince: null,
      Postcode: "NP18 2LX",
      CountryID: 1,
      Country: {
        ISOCode: "GB",
        ContinentCode: "EU",
        ID: 1,
        Title: "United Kingdom",
      },
      Latitude: 51.604,
      Longitude: -2.9217,
      ContactTelephone1: null,
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: null,
      RelatedURL: null,
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 162213,
        ConnectionTypeID: 33,
        ConnectionType: {
          FormalName: "IEC 62196-3 Configuration FF",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 33,
          Title: "CCS (Type 2)",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: null,
        Voltage: null,
        PowerKW: 50,
        CurrentTypeID: 30,
        CurrentType: {
          Description: "Direct Current",
          ID: 30,
          Title: "DC",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 162214,
        ConnectionTypeID: 2,
        ConnectionType: {
          FormalName: "IEC 62196-3 Configuration AA",
          IsDiscontinued: null,
          IsObsolete: null,
          ID: 2,
          Title: "CHAdeMO",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: null,
        Voltage: null,
        PowerKW: 50,
        CurrentTypeID: 30,
        CurrentType: {
          Description: "Direct Current",
          ID: 30,
          Title: "DC",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 162215,
        ConnectionTypeID: 1036,
        ConnectionType: {
          FormalName: "IEC 62196-2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 1036,
          Title: "Type 2 (Tethered Connector) ",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: null,
        Voltage: null,
        PowerKW: 43,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: 1,
        Comments: null,
      },
    ],
    NumberOfPoints: 2,
    GeneralComments: "Unit located in the Hotel car park.",
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 50,
    DateLastStatusUpdate: "2019-04-25T05:16:00Z",
    MetadataValues: null,
    DataQualityLevel: 1,
    DateCreated: "2019-02-09T06:16:00Z",
    SubmissionStatusTypeID: 200,
  },
  {
    DataProvider: {
      WebsiteURL: "http://openchargemap.org",
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 1,
        Title: "Manual Data Entry",
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License: "Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)",
      DateLastImported: null,
      ID: 1,
      Title: "Open Charge Map Contributors",
    },
    OperatorInfo: {
      WebsiteURL: "http://www.teslamotors.com",
      Comments: null,
      PhonePrimaryContact: null,
      PhoneSecondaryContact: null,
      IsPrivateIndividual: false,
      AddressInfo: null,
      BookingURL: null,
      ContactEmail: null,
      FaultReportEmail: null,
      IsRestrictedEdit: false,
      ID: 23,
      Title: "Tesla (Tesla-only charging)",
    },
    UsageType: {
      IsPayAtLocation: false,
      IsMembershipRequired: true,
      IsAccessKeyRequired: true,
      ID: 4,
      Title: "Public - Membership Required",
    },
    StatusType: {
      IsOperational: true,
      IsUserSelectable: true,
      ID: 50,
      Title: "Operational",
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 200,
      Title: "Submission Published",
    },
    UserComments: null,
    PercentageSimilarity: null,
    MediaItems: null,
    IsRecentlyVerified: false,
    DateLastVerified: "2018-10-03T19:46:00Z",
    ID: 105358,
    UUID: "8FCD8776-5B2E-4CC9-B6D0-11D934E45879",
    ParentChargePointID: null,
    DataProviderID: 1,
    DataProvidersReference: null,
    OperatorID: 23,
    OperatorsReference: "43964",
    UsageTypeID: 4,
    UsageCost: null,
    AddressInfo: {
      ID: 105704,
      Title: "Holiday Inn Newport",
      AddressLine1: "The Coldra",
      AddressLine2: null,
      Town: "Newport",
      StateOrProvince: null,
      Postcode: "NP18 2YG",
      CountryID: 1,
      Country: {
        ISOCode: "GB",
        ContinentCode: "EU",
        ID: 1,
        Title: "United Kingdom",
      },
      Latitude: 51.600069,
      Longitude: -2.927657,
      ContactTelephone1: "+44 163 341 2777",
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: null,
      RelatedURL: null,
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 148522,
        ConnectionTypeID: 30,
        ConnectionType: {
          FormalName: null,
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 30,
          Title: "Tesla (Model S/X)",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: null,
        Voltage: 230,
        PowerKW: 6,
        CurrentTypeID: 10,
        CurrentType: {
          Description: "Alternating Current - Single Phase",
          ID: 10,
          Title: "AC (Single-Phase)",
        },
        Quantity: 1,
        Comments: null,
      },
    ],
    NumberOfPoints: 1,
    GeneralComments: "1 Tesla Connector, up to 6kW.Available for customers. Please call ahead.",
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 50,
    DateLastStatusUpdate: "2018-10-03T19:46:00Z",
    MetadataValues: null,
    DataQualityLevel: 1,
    DateCreated: "2018-06-06T05:31:00Z",
    SubmissionStatusTypeID: 200,
  },
  {
    DataProvider: {
      WebsiteURL: "http://openchargemap.org",
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 1,
        Title: "Manual Data Entry",
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License: "Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)",
      DateLastImported: null,
      ID: 1,
      Title: "Open Charge Map Contributors",
    },
    OperatorInfo: {
      WebsiteURL: "https://www.bppulse.co.uk/",
      Comments: "Formerly known as Polar Network, or BP Chargemaster",
      PhonePrimaryContact: "01582 400331",
      PhoneSecondaryContact: null,
      IsPrivateIndividual: false,
      AddressInfo: null,
      BookingURL: null,
      ContactEmail: "polarenquiries@chargemasterplc.com",
      FaultReportEmail: "polarenquiries@chargemasterplc.com",
      IsRestrictedEdit: false,
      ID: 32,
      Title: "BP Pulse",
    },
    UsageType: {
      IsPayAtLocation: false,
      IsMembershipRequired: true,
      IsAccessKeyRequired: true,
      ID: 4,
      Title: "Public - Membership Required",
    },
    StatusType: {
      IsOperational: true,
      IsUserSelectable: true,
      ID: 50,
      Title: "Operational",
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 200,
      Title: "Submission Published",
    },
    UserComments: null,
    PercentageSimilarity: null,
    MediaItems: null,
    IsRecentlyVerified: false,
    DateLastVerified: "2019-06-20T05:33:00Z",
    ID: 100484,
    UUID: "6F99FC0C-AAD9-4F2F-A748-A76874F1DDB0",
    ParentChargePointID: null,
    DataProviderID: 1,
    DataProvidersReference: null,
    OperatorID: 32,
    OperatorsReference: "24107",
    UsageTypeID: 4,
    UsageCost: "£0.108/kWh; for Polar Plus subscription members only",
    AddressInfo: {
      ID: 100830,
      Title: "Holiday Inn Newport",
      AddressLine1: "Holiday Inn Newport",
      AddressLine2: null,
      Town: "The Coldra",
      StateOrProvince: "Newport",
      Postcode: "NP18 2YG",
      CountryID: 1,
      Country: {
        ISOCode: "GB",
        ContinentCode: "EU",
        ID: 1,
        Title: "United Kingdom",
      },
      Latitude: 51.599899,
      Longitude: -2.9279,
      ContactTelephone1: null,
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: null,
      RelatedURL: null,
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 141935,
        ConnectionTypeID: 33,
        ConnectionType: {
          FormalName: "IEC 62196-3 Configuration FF",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 33,
          Title: "CCS (Type 2)",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: null,
        Voltage: null,
        PowerKW: 50,
        CurrentTypeID: 30,
        CurrentType: {
          Description: "Direct Current",
          ID: 30,
          Title: "DC",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 141936,
        ConnectionTypeID: 2,
        ConnectionType: {
          FormalName: "IEC 62196-3 Configuration AA",
          IsDiscontinued: null,
          IsObsolete: null,
          ID: 2,
          Title: "CHAdeMO",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: null,
        Voltage: null,
        PowerKW: 50,
        CurrentTypeID: 30,
        CurrentType: {
          Description: "Direct Current",
          ID: 30,
          Title: "DC",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 141937,
        ConnectionTypeID: 1036,
        ConnectionType: {
          FormalName: "IEC 62196-2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 1036,
          Title: "Type 2 (Tethered Connector) ",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: null,
        Voltage: null,
        PowerKW: 43,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: 1,
        Comments: null,
      },
    ],
    NumberOfPoints: 1,
    GeneralComments: null,
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 50,
    DateLastStatusUpdate: "2019-06-20T05:33:00Z",
    MetadataValues: null,
    DataQualityLevel: 1,
    DateCreated: "2018-02-27T06:14:00Z",
    SubmissionStatusTypeID: 200,
  },
  {
    DataProvider: {
      WebsiteURL: "http://openchargemap.org",
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 1,
        Title: "Manual Data Entry",
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License: "Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)",
      DateLastImported: null,
      ID: 1,
      Title: "Open Charge Map Contributors",
    },
    OperatorInfo: {
      WebsiteURL: "http://zerocarbonworld.org/",
      Comments: "UK Charity promoting carbon reduction",
      PhonePrimaryContact: null,
      PhoneSecondaryContact: null,
      IsPrivateIndividual: false,
      AddressInfo: null,
      BookingURL: null,
      ContactEmail: "info@zerocarbonworld.com",
      FaultReportEmail: "info@zerocarbonworld.com",
      IsRestrictedEdit: null,
      ID: 19,
      Title: "Zero Carbon World",
    },
    UsageType: {
      IsPayAtLocation: true,
      IsMembershipRequired: false,
      IsAccessKeyRequired: false,
      ID: 5,
      Title: "Public - Pay At Location",
    },
    StatusType: {
      IsOperational: true,
      IsUserSelectable: true,
      ID: 50,
      Title: "Operational",
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 200,
      Title: "Submission Published",
    },
    UserComments: [
      {
        ID: 323,
        ChargePointID: 16495,
        CommentTypeID: 100,
        CommentType: {
          ID: 100,
          Title: "Suggested Change (Note To Editors)",
        },
        UserName: "Alexander Sims",
        Comment:
          "Charging is now free for all users\nParking is free for first 4 hours\nTesla connector could be labbeled at 'High Power' as 70A 240v is available.",
        Rating: 5,
        RelatedURL: null,
        DateCreated: "2013-05-08T15:04:06.687Z",
        User: null,
        CheckinStatusTypeID: null,
        CheckinStatusType: null,
        IsActionedByEditor: null,
      },
    ],
    PercentageSimilarity: null,
    MediaItems: null,
    IsRecentlyVerified: false,
    DateLastVerified: "2019-05-09T12:25:00Z",
    ID: 16495,
    UUID: "F746109C-3EEC-4FAC-B8AE-B9ED1319DB26",
    ParentChargePointID: null,
    DataProviderID: 1,
    DataProvidersReference: null,
    OperatorID: 19,
    OperatorsReference: null,
    UsageTypeID: 5,
    UsageCost: null,
    AddressInfo: {
      ID: 16840,
      Title: "Celtic Manor Resort",
      AddressLine1: "Coldra Woods",
      AddressLine2: "The Usk Valley",
      Town: "Newport",
      StateOrProvince: "Gwent",
      Postcode: "NP18 1HQ",
      CountryID: 1,
      Country: {
        ISOCode: "GB",
        ContinentCode: "EU",
        ID: 1,
        Title: "United Kingdom",
      },
      Latitude: 51.6022056,
      Longitude: -2.93138709999994,
      ContactTelephone1: "01633 413000",
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: null,
      RelatedURL: "http://www.celtic-manor.com/",
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 14920,
        ConnectionTypeID: 33,
        ConnectionType: {
          FormalName: "IEC 62196-3 Configuration FF",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 33,
          Title: "CCS (Type 2)",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: 63,
        Voltage: 240,
        PowerKW: 43,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 14921,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 32,
        Voltage: 240,
        PowerKW: 22,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 176512,
        ConnectionTypeID: 1036,
        ConnectionType: {
          FormalName: "IEC 62196-2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 1036,
          Title: "Type 2 (Tethered Connector) ",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 32,
        Voltage: 230,
        PowerKW: 22,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: 2,
        Comments: null,
      },
      {
        ID: 176513,
        ConnectionTypeID: 3,
        ConnectionType: {
          FormalName: "BS1363 / Type G",
          IsDiscontinued: null,
          IsObsolete: null,
          ID: 3,
          Title: "BS1363 3 Pin 13 Amp",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 13,
        Voltage: 230,
        PowerKW: 3,
        CurrentTypeID: 10,
        CurrentType: {
          Description: "Alternating Current - Single Phase",
          ID: 10,
          Title: "AC (Single-Phase)",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 176516,
        ConnectionTypeID: 3,
        ConnectionType: {
          FormalName: "BS1363 / Type G",
          IsDiscontinued: null,
          IsObsolete: null,
          ID: 3,
          Title: "BS1363 3 Pin 13 Amp",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 13,
        Voltage: 230,
        PowerKW: 3,
        CurrentTypeID: 10,
        CurrentType: {
          Description: "Alternating Current - Single Phase",
          ID: 10,
          Title: "AC (Single-Phase)",
        },
        Quantity: 1,
        Comments: null,
      },
    ],
    NumberOfPoints: 4,
    GeneralComments: "charging points shared in 4 parking bays",
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 50,
    DateLastStatusUpdate: "2019-05-09T12:25:00Z",
    MetadataValues: null,
    DataQualityLevel: 1,
    DateCreated: "2013-04-29T08:58:00Z",
    SubmissionStatusTypeID: 200,
  },
  {
    DataProvider: {
      WebsiteURL: "http://openchargemap.org",
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 1,
        Title: "Manual Data Entry",
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License: "Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)",
      DateLastImported: null,
      ID: 1,
      Title: "Open Charge Map Contributors",
    },
    OperatorInfo: {
      WebsiteURL: "http://www.pod-point.com/",
      Comments: "Part of Groupe EDF",
      PhonePrimaryContact: "020 7247 4114",
      PhoneSecondaryContact: null,
      IsPrivateIndividual: false,
      AddressInfo: null,
      BookingURL: null,
      ContactEmail: "enquiries@pod-point.com",
      FaultReportEmail: "enquiries@pod-point.com",
      IsRestrictedEdit: false,
      ID: 3,
      Title: "POD Point (UK)",
    },
    UsageType: {
      IsPayAtLocation: false,
      IsMembershipRequired: true,
      IsAccessKeyRequired: true,
      ID: 4,
      Title: "Public - Membership Required",
    },
    StatusType: {
      IsOperational: true,
      IsUserSelectable: true,
      ID: 50,
      Title: "Operational",
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 200,
      Title: "Submission Published",
    },
    UserComments: null,
    PercentageSimilarity: null,
    MediaItems: null,
    IsRecentlyVerified: true,
    DateLastVerified: "2022-11-08T06:22:00Z",
    ID: 194608,
    UUID: "E2B897AD-7460-4AD5-B802-1C2FEB63B1F3",
    ParentChargePointID: null,
    DataProviderID: 1,
    DataProvidersReference: null,
    OperatorID: 3,
    OperatorsReference: "PG-105303,PG-105743,PG-105746",
    UsageTypeID: 4,
    UsageCost: "£0.50/kWh",
    AddressInfo: {
      ID: 194967,
      Title: "Holiday Inn Newport",
      AddressLine1: "The Coldra",
      AddressLine2: null,
      Town: "Newport",
      StateOrProvince: "Wales",
      Postcode: "NP18 2YG",
      CountryID: 1,
      Country: {
        ISOCode: "GB",
        ContinentCode: "EU",
        ID: 1,
        Title: "United Kingdom",
      },
      Latitude: 51.59952068,
      Longitude: -2.92687531,
      ContactTelephone1: null,
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: null,
      RelatedURL: null,
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 317305,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: "PG-105303",
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 16,
        Voltage: 400,
        PowerKW: 11,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: 1,
        Comments: "Chet-Colt",
      },
      {
        ID: 320163,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: "PG-105743",
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 16,
        Voltage: 400,
        PowerKW: 11,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: 1,
        Comments: "Finn-Zara",
      },
      {
        ID: 323849,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: "PG-105746",
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 16,
        Voltage: 400,
        PowerKW: 11,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: 1,
        Comments: "Gene-Reno",
      },
    ],
    NumberOfPoints: 3,
    GeneralComments: null,
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 50,
    DateLastStatusUpdate: "2022-11-08T06:22:00Z",
    MetadataValues: null,
    DataQualityLevel: 1,
    DateCreated: "2022-08-08T09:01:00Z",
    SubmissionStatusTypeID: 200,
  },
  {
    DataProvider: {
      WebsiteURL: "http://openchargemap.org",
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 1,
        Title: "Manual Data Entry",
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License: "Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)",
      DateLastImported: null,
      ID: 1,
      Title: "Open Charge Map Contributors",
    },
    OperatorInfo: {
      WebsiteURL: "http://www.pod-point.com/",
      Comments: "Part of Groupe EDF",
      PhonePrimaryContact: "020 7247 4114",
      PhoneSecondaryContact: null,
      IsPrivateIndividual: false,
      AddressInfo: null,
      BookingURL: null,
      ContactEmail: "enquiries@pod-point.com",
      FaultReportEmail: "enquiries@pod-point.com",
      IsRestrictedEdit: false,
      ID: 3,
      Title: "POD Point (UK)",
    },
    UsageType: {
      IsPayAtLocation: false,
      IsMembershipRequired: true,
      IsAccessKeyRequired: true,
      ID: 4,
      Title: "Public - Membership Required",
    },
    StatusType: {
      IsOperational: true,
      IsUserSelectable: true,
      ID: 50,
      Title: "Operational",
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 200,
      Title: "Submission Published",
    },
    UserComments: null,
    PercentageSimilarity: null,
    MediaItems: null,
    IsRecentlyVerified: true,
    DateLastVerified: "2022-12-06T06:23:00Z",
    ID: 210245,
    UUID: "02A52864-AF91-43A9-9FA5-21E4496EFA9D",
    ParentChargePointID: null,
    DataProviderID: 1,
    DataProvidersReference: null,
    OperatorID: 3,
    OperatorsReference: "PG-70617,PG-89820",
    UsageTypeID: 4,
    UsageCost: "£0.28/kWh",
    AddressInfo: {
      ID: 210625,
      Title: "Tesco Extra-Newport Spytty",
      AddressLine1: "Spytty Road",
      AddressLine2: null,
      Town: "Newport",
      StateOrProvince: null,
      Postcode: "NP19 4TX",
      CountryID: 1,
      Country: {
        ISOCode: "GB",
        ContinentCode: "EU",
        ID: 1,
        Title: "United Kingdom",
      },
      Latitude: 51.57658057,
      Longitude: -2.94751755,
      ContactTelephone1: null,
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: null,
      RelatedURL: null,
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 350078,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: "PG-70617",
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 32,
        Voltage: 230,
        PowerKW: 7,
        CurrentTypeID: 10,
        CurrentType: {
          Description: "Alternating Current - Single Phase",
          ID: 10,
          Title: "AC (Single-Phase)",
        },
        Quantity: 2,
        Comments: "Myla-Niki",
      },
      {
        ID: 350079,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: "PG-89820",
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 32,
        Voltage: 230,
        PowerKW: 7,
        CurrentTypeID: 10,
        CurrentType: {
          Description: "Alternating Current - Single Phase",
          ID: 10,
          Title: "AC (Single-Phase)",
        },
        Quantity: 2,
        Comments: "Isla-Enya",
      },
    ],
    NumberOfPoints: 2,
    GeneralComments:
      "This is an open charge unit installed at Tesco Extra site at Spytty Road, Newport",
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 50,
    DateLastStatusUpdate: "2022-12-06T06:23:00Z",
    MetadataValues: null,
    DataQualityLevel: 1,
    DateCreated: "2022-12-06T06:23:00Z",
    SubmissionStatusTypeID: 200,
  },
  {
    DataProvider: {
      WebsiteURL: "http://openchargemap.org",
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 1,
        Title: "Manual Data Entry",
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License: "Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)",
      DateLastImported: null,
      ID: 1,
      Title: "Open Charge Map Contributors",
    },
    OperatorInfo: {
      WebsiteURL: "http://www.pod-point.com/",
      Comments: "Part of Groupe EDF",
      PhonePrimaryContact: "020 7247 4114",
      PhoneSecondaryContact: null,
      IsPrivateIndividual: false,
      AddressInfo: null,
      BookingURL: null,
      ContactEmail: "enquiries@pod-point.com",
      FaultReportEmail: "enquiries@pod-point.com",
      IsRestrictedEdit: false,
      ID: 3,
      Title: "POD Point (UK)",
    },
    UsageType: {
      IsPayAtLocation: false,
      IsMembershipRequired: false,
      IsAccessKeyRequired: false,
      ID: 6,
      Title: "Private - For Staff, Visitors or Customers",
    },
    StatusType: {
      IsOperational: true,
      IsUserSelectable: true,
      ID: 50,
      Title: "Operational",
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 200,
      Title: "Submission Published",
    },
    UserComments: null,
    PercentageSimilarity: null,
    MediaItems: null,
    IsRecentlyVerified: false,
    DateLastVerified: "2018-04-18T05:48:00Z",
    ID: 102157,
    UUID: "6387ECB7-7BCB-4173-8FD5-ED0E4568F584",
    ParentChargePointID: null,
    DataProviderID: 1,
    DataProvidersReference: null,
    OperatorID: 3,
    OperatorsReference: "PG-81796",
    UsageTypeID: 6,
    UsageCost: "Free",
    AddressInfo: {
      ID: 102503,
      Title: "Wessex Newport-Hyundai",
      AddressLine1: "Seven Styles Avenue",
      AddressLine2: null,
      Town: "Newport",
      StateOrProvince: null,
      Postcode: "NP19 4QR",
      CountryID: 1,
      Country: {
        ISOCode: "GB",
        ContinentCode: "EU",
        ID: 1,
        Title: "United Kingdom",
      },
      Latitude: 51.575345,
      Longitude: -2.944849,
      ContactTelephone1: null,
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: null,
      RelatedURL: null,
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 144176,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 32,
        Voltage: 230,
        PowerKW: 7,
        CurrentTypeID: 10,
        CurrentType: {
          Description: "Alternating Current - Single Phase",
          ID: 10,
          Title: "AC (Single-Phase)",
        },
        Quantity: 2,
        Comments: null,
      },
    ],
    NumberOfPoints: 2,
    GeneralComments:
      "This is an open charge unit installed at the Wessex Newport - Hyundai dealership in Seven Styles Avenue, Newport Retail Park, Gwent, Newport",
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 50,
    DateLastStatusUpdate: "2018-04-18T05:48:00Z",
    MetadataValues: null,
    DataQualityLevel: 1,
    DateCreated: "2018-04-18T05:48:00Z",
    SubmissionStatusTypeID: 200,
  },
  {
    DataProvider: {
      WebsiteURL: "http://openchargemap.org",
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 1,
        Title: "Manual Data Entry",
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License: "Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)",
      DateLastImported: null,
      ID: 1,
      Title: "Open Charge Map Contributors",
    },
    OperatorInfo: {
      WebsiteURL: "http://www.pod-point.com/",
      Comments: "Part of Groupe EDF",
      PhonePrimaryContact: "020 7247 4114",
      PhoneSecondaryContact: null,
      IsPrivateIndividual: false,
      AddressInfo: null,
      BookingURL: null,
      ContactEmail: "enquiries@pod-point.com",
      FaultReportEmail: "enquiries@pod-point.com",
      IsRestrictedEdit: false,
      ID: 3,
      Title: "POD Point (UK)",
    },
    UsageType: {
      IsPayAtLocation: false,
      IsMembershipRequired: false,
      IsAccessKeyRequired: false,
      ID: 6,
      Title: "Private - For Staff, Visitors or Customers",
    },
    StatusType: {
      IsOperational: true,
      IsUserSelectable: true,
      ID: 50,
      Title: "Operational",
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 200,
      Title: "Submission Published",
    },
    UserComments: null,
    PercentageSimilarity: null,
    MediaItems: null,
    IsRecentlyVerified: false,
    DateLastVerified: "2017-07-27T17:51:00Z",
    ID: 90908,
    UUID: "92177C4A-70CC-44CC-9B9D-637F9B9B8BDF",
    ParentChargePointID: null,
    DataProviderID: 1,
    DataProvidersReference: null,
    OperatorID: 3,
    OperatorsReference: "PG-91253",
    UsageTypeID: 6,
    UsageCost: "Free",
    AddressInfo: {
      ID: 91254,
      Title: "Capitol Skoda",
      AddressLine1: "Leeway Industrial Estate",
      AddressLine2: null,
      Town: "Gwent",
      StateOrProvince: null,
      Postcode: "NP19 4SL",
      CountryID: 1,
      Country: {
        ISOCode: "GB",
        ContinentCode: "EU",
        ID: 1,
        Title: "United Kingdom",
      },
      Latitude: 51.568227,
      Longitude: -2.950055,
      ContactTelephone1: null,
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: null,
      RelatedURL: null,
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 128960,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 32,
        Voltage: 230,
        PowerKW: 7,
        CurrentTypeID: 10,
        CurrentType: {
          Description: "Alternating Current - Single Phase",
          ID: 10,
          Title: "AC (Single-Phase)",
        },
        Quantity: 1,
        Comments: null,
      },
    ],
    NumberOfPoints: 1,
    GeneralComments:
      "This is an open charge unit installed at the Capitol Skoda site in Leeway Industrial Estate, Lee Way, Newport, Gwent",
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 50,
    DateLastStatusUpdate: "2017-07-27T17:51:00Z",
    MetadataValues: null,
    DataQualityLevel: 1,
    DateCreated: "2017-07-27T17:51:00Z",
    SubmissionStatusTypeID: 200,
  },
  {
    DataProvider: {
      WebsiteURL: "http://openchargemap.org",
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 1,
        Title: "Manual Data Entry",
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License: "Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0)",
      DateLastImported: null,
      ID: 1,
      Title: "Open Charge Map Contributors",
    },
    OperatorInfo: {
      WebsiteURL: "https://ospreycharging.co.uk/ev-drivers/",
      Comments: "GB-OSP,formerly known as Engenie",
      PhonePrimaryContact: "0330 010 1757",
      PhoneSecondaryContact: null,
      IsPrivateIndividual: false,
      AddressInfo: null,
      BookingURL: null,
      ContactEmail: "info@engenie.co.uk",
      FaultReportEmail: null,
      IsRestrictedEdit: false,
      ID: 203,
      Title: "Osprey Charging",
    },
    UsageType: {
      IsPayAtLocation: true,
      IsMembershipRequired: false,
      IsAccessKeyRequired: false,
      ID: 5,
      Title: "Public - Pay At Location",
    },
    StatusType: {
      IsOperational: true,
      IsUserSelectable: true,
      ID: 50,
      Title: "Operational",
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 200,
      Title: "Submission Published",
    },
    UserComments: null,
    PercentageSimilarity: null,
    MediaItems: null,
    IsRecentlyVerified: false,
    DateLastVerified: "2021-06-21T16:43:00Z",
    ID: 134311,
    UUID: "AD77A130-E320-48CC-9B12-E216106331FD",
    ParentChargePointID: null,
    DataProviderID: 1,
    DataProvidersReference: null,
    OperatorID: 203,
    OperatorsReference: null,
    UsageTypeID: 5,
    UsageCost: "£0.36/kWh",
    AddressInfo: {
      ID: 134657,
      Title: "Blaina Wharf Newport Pub & Restaurant",
      AddressLine1: "East Dock Road",
      AddressLine2: null,
      Town: "Newport",
      StateOrProvince: null,
      Postcode: "NP20 2FR",
      CountryID: 1,
      Country: {
        ISOCode: "GB",
        ContinentCode: "EU",
        ID: 1,
        Title: "United Kingdom",
      },
      Latitude: 51.57652,
      Longitude: -2.97945,
      ContactTelephone1: null,
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: null,
      RelatedURL: "",
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 187959,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: "ENG00041-3",
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 32,
        Voltage: 400,
        PowerKW: 22,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 187986,
        ConnectionTypeID: 33,
        ConnectionType: {
          FormalName: "IEC 62196-3 Configuration FF",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 33,
          Title: "CCS (Type 2)",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: 125,
        Voltage: 400,
        PowerKW: 50,
        CurrentTypeID: 30,
        CurrentType: {
          Description: "Direct Current",
          ID: 30,
          Title: "DC",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 187987,
        ConnectionTypeID: 2,
        ConnectionType: {
          FormalName: "IEC 62196-3 Configuration AA",
          IsDiscontinued: null,
          IsObsolete: null,
          ID: 2,
          Title: "CHAdeMO",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: 125,
        Voltage: 400,
        PowerKW: 50,
        CurrentTypeID: 30,
        CurrentType: {
          Description: "Direct Current",
          ID: 30,
          Title: "DC",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 273401,
        ConnectionTypeID: 33,
        ConnectionType: {
          FormalName: "IEC 62196-3 Configuration FF",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 33,
          Title: "CCS (Type 2)",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: null,
        Voltage: null,
        PowerKW: 50,
        CurrentTypeID: 30,
        CurrentType: {
          Description: "Direct Current",
          ID: 30,
          Title: "DC",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 273402,
        ConnectionTypeID: 2,
        ConnectionType: {
          FormalName: "IEC 62196-3 Configuration AA",
          IsDiscontinued: null,
          IsObsolete: null,
          ID: 2,
          Title: "CHAdeMO",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 3,
        Level: {
          Comments: "40KW and Higher",
          IsFastChargeCapable: true,
          ID: 3,
          Title: "Level 3:  High (Over 40kW)",
        },
        Amps: null,
        Voltage: null,
        PowerKW: 50,
        CurrentTypeID: 30,
        CurrentType: {
          Description: "Direct Current",
          ID: 30,
          Title: "DC",
        },
        Quantity: 1,
        Comments: null,
      },
      {
        ID: 273403,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: null,
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 32,
        Voltage: 400,
        PowerKW: 22,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: 1,
        Comments: null,
      },
    ],
    NumberOfPoints: null,
    GeneralComments: null,
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 50,
    DateLastStatusUpdate: "2021-06-21T16:43:00Z",
    MetadataValues: [
      {
        ID: 5066,
        MetadataFieldID: 4,
        ItemValue:
          "Contains public sector information licensed under the Open Government Licence v2.0. http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/",
        MetadataFieldOption: null,
        MetadataFieldOptionID: null,
      },
    ],
    DataQualityLevel: 3,
    DateCreated: "2019-11-08T08:03:00Z",
    SubmissionStatusTypeID: 200,
  },
  {
    DataProvider: {
      WebsiteURL: "http://chargepoints.dft.gov.uk",
      Comments: null,
      DataProviderStatusType: {
        IsProviderEnabled: true,
        ID: 20,
        Title: "Automated Import",
      },
      IsRestrictedEdit: false,
      IsOpenDataLicensed: true,
      IsApprovedImport: true,
      License:
        "Contains public sector information licensed under the Open Government Licence v2.0.",
      DateLastImported: "2022-08-23T11:01:46.157Z",
      ID: 18,
      Title: "UK National Charge Point Registry",
    },
    OperatorInfo: null,
    UsageType: {
      IsPayAtLocation: true,
      IsMembershipRequired: false,
      IsAccessKeyRequired: false,
      ID: 5,
      Title: "Public - Pay At Location",
    },
    StatusType: {
      IsOperational: null,
      IsUserSelectable: true,
      ID: 0,
      Title: "Unknown",
    },
    SubmissionStatus: {
      IsLive: true,
      ID: 100,
      Title: "Imported and Published",
    },
    UserComments: null,
    PercentageSimilarity: null,
    MediaItems: null,
    IsRecentlyVerified: true,
    DateLastVerified: "2022-08-23T11:10:00Z",
    ID: 200645,
    UUID: "1BBCA4FE-0191-4CAD-B065-D765D97AF34D",
    ParentChargePointID: null,
    DataProviderID: 18,
    DataProvidersReference: "a22d9204f4af59e9d8f1dbb2aca4b150",
    OperatorID: null,
    OperatorsReference: null,
    UsageTypeID: 5,
    UsageCost: null,
    AddressInfo: {
      ID: 201004,
      Title: "Mill Parade",
      AddressLine1: "Mill Parade",
      AddressLine2: null,
      Town: "Newport",
      StateOrProvince: null,
      Postcode: "NP20 2JS",
      CountryID: 1,
      Country: {
        ISOCode: "GB",
        ContinentCode: "EU",
        ID: 1,
        Title: "United Kingdom",
      },
      Latitude: 51.5713,
      Longitude: -2.98795,
      ContactTelephone1: null,
      ContactTelephone2: null,
      ContactEmail: null,
      AccessComments: "",
      RelatedURL: "http://www.silverstonegreenenergy.com/",
      Distance: null,
      DistanceUnit: 0,
    },
    Connections: [
      {
        ID: 334585,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: "DC380101",
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 32,
        Voltage: 400,
        PowerKW: 22,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: null,
        Comments: null,
      },
      {
        ID: 334586,
        ConnectionTypeID: 25,
        ConnectionType: {
          FormalName: "IEC 62196-2 Type 2",
          IsDiscontinued: false,
          IsObsolete: false,
          ID: 25,
          Title: "Type 2 (Socket Only)",
        },
        Reference: "DC380102",
        StatusTypeID: 50,
        StatusType: {
          IsOperational: true,
          IsUserSelectable: true,
          ID: 50,
          Title: "Operational",
        },
        LevelID: 2,
        Level: {
          Comments: "Over 2 kW, usually non-domestic socket type",
          IsFastChargeCapable: false,
          ID: 2,
          Title: "Level 2 : Medium (Over 2kW)",
        },
        Amps: 32,
        Voltage: 400,
        PowerKW: 22,
        CurrentTypeID: 20,
        CurrentType: {
          Description: "Alternating Current - Three Phase",
          ID: 20,
          Title: "AC (Three-Phase)",
        },
        Quantity: null,
        Comments: null,
      },
    ],
    NumberOfPoints: null,
    GeneralComments: null,
    DatePlanned: null,
    DateLastConfirmed: null,
    StatusTypeID: 0,
    DateLastStatusUpdate: "2022-08-23T11:10:00Z",
    MetadataValues: [
      {
        ID: 21067,
        MetadataFieldID: 4,
        ItemValue:
          "Contains public sector information licensed under the Open Government Licence v2.0. http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/",
        MetadataFieldOption: null,
        MetadataFieldOptionID: null,
      },
    ],
    DataQualityLevel: 3,
    DateCreated: "2022-08-23T11:10:00Z",
    SubmissionStatusTypeID: 100,
  },
];
