export const containerStyle = {
  maxWidth: "100%",
  minHeight: "100%",
};

export const londonCoords = {
  lat: 51.519977,
  lng: -0.128115,
};

const obj = {
  AddressInfo: {
    ID: 115571,
    Title: "Coldra Court Hotel By Celtic Manor",
    AddressLine1: "Langstone",
    AddressLine2: null,
    Town: "Newport",
    StateOrProvince: null,
    Postcode: "NP18 2LX",
    CountryID: 1,
    Country: {
      ISOCode: "GB",
      ContinentCode: "EU",
      ID: 1,
      Title: "United Kingdom",
    },
    Latitude: 51.604,
    Longitude: -2.9217,
    ContactTelephone1: null,
    ContactTelephone2: null,
    ContactEmail: null,
    AccessComments: null,
    RelatedURL: null,
    Distance: null,
    DistanceUnit: 0,
  },
  Connections: [
    {
      ID: 162213,
      ConnectionTypeID: 33,
      ConnectionType: {
        FormalName: "IEC 62196-3 Configuration FF",
        IsDiscontinued: false,
        IsObsolete: false,
        ID: 33,
        Title: "CCS (Type 2)",
      },
      Reference: null,
      StatusTypeID: 50,
      StatusType: {
        IsOperational: true,
        IsUserSelectable: true,
        ID: 50,
        Title: "Operational",
      },
      LevelID: 3,
      Level: {
        Comments: "40KW and Higher",
        IsFastChargeCapable: true,
        ID: 3,
        Title: "Level 3:  High (Over 40kW)",
      },
      Amps: null,
      Voltage: null,
      PowerKW: 50,
      CurrentTypeID: 30,
      CurrentType: {
        Description: "Direct Current",
        ID: 30,
        Title: "DC",
      },
      Quantity: 1,
      Comments: null,
    },
    {
      ID: 162214,
      ConnectionTypeID: 2,
      ConnectionType: {
        FormalName: "IEC 62196-3 Configuration AA",
        IsDiscontinued: null,
        IsObsolete: null,
        ID: 2,
        Title: "CHAdeMO",
      },
      Reference: null,
      StatusTypeID: 50,
      StatusType: {
        IsOperational: true,
        IsUserSelectable: true,
        ID: 50,
        Title: "Operational",
      },
      LevelID: 3,
      Level: {
        Comments: "40KW and Higher",
        IsFastChargeCapable: true,
        ID: 3,
        Title: "Level 3:  High (Over 40kW)",
      },
      Amps: null,
      Voltage: null,
      PowerKW: 50,
      CurrentTypeID: 30,
      CurrentType: {
        Description: "Direct Current",
        ID: 30,
        Title: "DC",
      },
      Quantity: 1,
      Comments: null,
    },
    {
      ID: 162215,
      ConnectionTypeID: 1036,
      ConnectionType: {
        FormalName: "IEC 62196-2",
        IsDiscontinued: false,
        IsObsolete: false,
        ID: 1036,
        Title: "Type 2 (Tethered Connector) ",
      },
      Reference: null,
      StatusTypeID: 50,
      StatusType: {
        IsOperational: true,
        IsUserSelectable: true,
        ID: 50,
        Title: "Operational",
      },
      LevelID: 3,
      Level: {
        Comments: "40KW and Higher",
        IsFastChargeCapable: true,
        ID: 3,
        Title: "Level 3:  High (Over 40kW)",
      },
      Amps: null,
      Voltage: null,
      PowerKW: 43,
      CurrentTypeID: 20,
      CurrentType: {
        Description: "Alternating Current - Three Phase",
        ID: 20,
        Title: "AC (Three-Phase)",
      },
      Quantity: 1,
      Comments: null,
    },
  ],
  NumberOfPoints: 2,
  GeneralComments: "Unit located in the Hotel car park.",
  DatePlanned: null,
  DateLastConfirmed: null,
  StatusTypeID: 50,
  DateLastStatusUpdate: "2019-04-25T05:16:00Z",
  MetadataValues: null,
  DataQualityLevel: 1,
  DateCreated: "2019-02-09T06:16:00Z",
  SubmissionStatusTypeID: 200,
};

export const data = new Array(10).fill({
  ID: 115571,
  Title: "Coldra Court Hotel By Celtic Manor",
  AddressLine1: "Langstone",
  AddressLine2: null,
  Town: "Newport",
  StateOrProvince: null,
  Postcode: "NP18 2LX",
  CountryID: 1,
  Country: {
    ISOCode: "GB",
    ContinentCode: "EU",
    ID: 1,
    Title: "United Kingdom",
  },
  Latitude: 51.604,
  Longitude: -2.9217,
  ContactTelephone1: null,
  ContactTelephone2: null,
  ContactEmail: null,
  AccessComments: null,
  RelatedURL: null,
  Distance: null,
  DistanceUnit: 0,
});
